"""Tests for script dict field contract.

The script dict generated by Claude has episode_id and title at ROOT level,
NOT inside metadata. Every module that reads these fields must look at the
root, not metadata.

Script structure:
{
    "episode_id": "DRAFT-EP-001",   <-- ROOT
    "title": "My Episode",          <-- ROOT
    "metadata": {
        "total_duration_seconds": 35,
        "characters_featured": [...],
        "primary_location": "...",
        ...
        // NO episode_id or title here
    }
}
"""

import json
import os
import tempfile
from unittest.mock import patch, MagicMock

import pytest


# A minimal but realistic script dict matching the actual Claude output structure
SAMPLE_SCRIPT = {
    "episode_id": "DRAFT-EP-001",
    "title": "Market Research",
    "slug": "market-research",
    "created_at": "2026-02-17T00:00:00Z",
    "version": 1,
    "generation_params": {
        "character_a": "oinks",
        "character_b": "chubs",
        "location": "town_square",
        "situation": "everyday_life",
        "punchline_type": "deadpan",
        "trending_tie_in": None,
        "seasonal_theme": None,
        "continuity_callbacks": [],
    },
    "duration_target_seconds": 35,
    "scenes": [
        {
            "scene_number": 1,
            "duration_seconds": 12,
            "background": "town_square",
            "characters_present": ["oinks", "chubs"],
            "character_positions": {"oinks": "center_left", "chubs": "center_right"},
            "character_animations": {"oinks": "idle", "chubs": "excited"},
            "action_description": "Test scene.",
            "dialogue": [
                {"character": "oinks", "text": "Hello", "animation_trigger": "talking", "duration_ms": 2000}
            ],
            "sfx_triggers": [],
            "music": "main_theme.wav",
        }
    ],
    "end_card": {
        "duration_seconds": 3,
        "text": "Follow for more island chaos!",
        "background": "endcard_template.png",
    },
    "continuity_log": {
        "events": ["Chubs tried to monetize lunch"],
        "new_running_gags": [],
        "character_developments": [],
    },
    "metadata": {
        "total_duration_seconds": 35,
        "characters_featured": ["oinks", "chubs"],
        "primary_location": "town_square",
        "content_pillar": "everyday_life",
        "punchline_type": "deadpan",
    },
}


# ---------------------------------------------------------------------------
# composer.py must read episode_id and title from script root
# ---------------------------------------------------------------------------

class TestComposerReadsRoot:
    """compose_episode must get episode_id and title from script root, not metadata."""

    def test_episode_id_from_root(self):
        """Composer must read episode_id from script root."""
        from src.video_assembler.composer import compose_episode

        script = SAMPLE_SCRIPT.copy()
        # metadata has no episode_id — only root does
        assert "episode_id" not in script["metadata"]
        assert script["episode_id"] == "DRAFT-EP-001"

        # We can't run compose_episode (needs FFmpeg), but we can verify
        # the code reads from the right place by checking the internal logic
        metadata = script.get("metadata", {})
        root_id = script.get("episode_id", "MISSING")
        metadata_id = metadata.get("episode_id", "MISSING")

        assert root_id == "DRAFT-EP-001"
        assert metadata_id == "MISSING", \
            "episode_id must NOT be in metadata — it's at the script root"

    def test_title_from_root(self):
        """Composer must read title from script root."""
        script = SAMPLE_SCRIPT.copy()
        assert "title" not in script["metadata"]
        assert script["title"] == "Market Research"

        metadata = script.get("metadata", {})
        root_title = script.get("title", "MISSING")
        metadata_title = metadata.get("title", "MISSING")

        assert root_title == "Market Research"
        assert metadata_title == "MISSING", \
            "title must NOT be in metadata — it's at the script root"


# ---------------------------------------------------------------------------
# variant_generator.py must read episode_id from script root
# ---------------------------------------------------------------------------

class TestVariantGeneratorReadsRoot:
    """Variant generator must get episode_id from script root."""

    def test_episode_id_used_in_output_name(self):
        """Output name must use the actual episode_id, not 'ep000'."""
        # The variant generator reads:
        #   episode_id = script.get("metadata", {}).get("episode_id", "EP000").lower()
        # This falls back to "ep000" since metadata has no episode_id
        from src.video_assembler import variant_generator

        script = SAMPLE_SCRIPT.copy()
        episode_id = script.get("episode_id", "EP000").lower()
        wrong_id = script.get("metadata", {}).get("episode_id", "EP000").lower()

        assert episode_id == "draft-ep-001"
        assert wrong_id == "ep000", \
            "Reading from metadata gives wrong fallback — proves the bug"


# ---------------------------------------------------------------------------
# storyboard/renderer.py must read from script root
# ---------------------------------------------------------------------------

class TestStoryboardReadsRoot:
    """Storyboard renderer must read episode_id and title from root."""

    def test_storyboard_title_not_fallback(self):
        """Storyboard title text must be 'DRAFT-EP-001: Market Research', not '?: Untitled'."""
        script = SAMPLE_SCRIPT.copy()
        # Current code: metadata.get("episode_id", "?") → "?"
        # Fixed code: script.get("episode_id", "?") → "DRAFT-EP-001"
        metadata = script.get("metadata", {})
        wrong_id = metadata.get("episode_id", "?")
        wrong_title = metadata.get("title", "Untitled")
        correct_id = script.get("episode_id", "?")
        correct_title = script.get("title", "Untitled")

        assert wrong_id == "?", "Proves the bug: metadata has no episode_id"
        assert wrong_title == "Untitled", "Proves the bug: metadata has no title"
        assert correct_id == "DRAFT-EP-001"
        assert correct_title == "Market Research"


# ---------------------------------------------------------------------------
# metadata/generator.py must read from script root
# ---------------------------------------------------------------------------

class TestMetadataGeneratorReadsRoot:
    """Metadata generator must read episode_id and title from root."""

    def test_youtube_description_has_real_episode_id(self):
        """YouTube description must contain the actual episode_id, not 'EP000'."""
        script = SAMPLE_SCRIPT.copy()
        metadata = script.get("metadata", {})

        wrong_id = metadata.get("episode_id", "EP000")
        correct_id = script.get("episode_id", "EP000")

        assert wrong_id == "EP000", "Proves the bug: fallback used"
        assert correct_id == "DRAFT-EP-001"

    def test_title_not_untitled(self):
        """Title must be 'Market Research', not 'Untitled'."""
        script = SAMPLE_SCRIPT.copy()
        metadata = script.get("metadata", {})

        wrong_title = metadata.get("title", "Untitled")
        correct_title = script.get("title", "Untitled")

        assert wrong_title == "Untitled", "Proves the bug: fallback used"
        assert correct_title == "Market Research"


# ---------------------------------------------------------------------------
# continuity/engine.py must read from script root
# ---------------------------------------------------------------------------

class TestContinuityReadsRoot:
    """log_episode must read episode_id and title from script root."""

    def test_continuity_episode_id(self):
        """Continuity must log real episode_id, not '?'."""
        script = SAMPLE_SCRIPT.copy()
        metadata = script.get("metadata", {})

        wrong_id = metadata.get("episode_id", "?")
        correct_id = script.get("episode_id", "?")

        assert wrong_id == "?", "Proves the bug"
        assert correct_id == "DRAFT-EP-001"


# ---------------------------------------------------------------------------
# pipeline/orchestrator.py log_episode_to_index must read from script root
# ---------------------------------------------------------------------------

class TestOrchestratorReadsRoot:
    """log_episode_to_index must read episode_id and title from root."""

    def test_index_stores_real_episode_id(self):
        """Episode index must store real episode_id, not '?'."""
        from src.pipeline.orchestrator import log_episode_to_index

        script = SAMPLE_SCRIPT.copy()

        with tempfile.TemporaryDirectory() as tmpdir:
            index_path = os.path.join(tmpdir, "episodes", "index.json")
            os.makedirs(os.path.dirname(index_path))
            with open(index_path, "w") as f:
                json.dump({"next_episode_number": 1, "episodes": []}, f)

            with patch("src.pipeline.orchestrator.DATA_DIR", tmpdir):
                log_episode_to_index(script)

            with open(index_path, "r") as f:
                data = json.load(f)

            assert data["episodes"][0]["episode_id"] == "DRAFT-EP-001", \
                "Must store actual episode_id from script root, not '?' fallback"

    def test_index_stores_real_title(self):
        """Episode index must store real title, not 'Untitled'."""
        from src.pipeline.orchestrator import log_episode_to_index

        script = SAMPLE_SCRIPT.copy()

        with tempfile.TemporaryDirectory() as tmpdir:
            index_path = os.path.join(tmpdir, "episodes", "index.json")
            os.makedirs(os.path.dirname(index_path))
            with open(index_path, "w") as f:
                json.dump({"next_episode_number": 1, "episodes": []}, f)

            with patch("src.pipeline.orchestrator.DATA_DIR", tmpdir):
                log_episode_to_index(script)

            with open(index_path, "r") as f:
                data = json.load(f)

            assert data["episodes"][0]["title"] == "Market Research", \
                "Must store actual title from script root, not 'Untitled' fallback"
